package avro

import "github.com/elodina/go-avro"

type LogLine struct {
	Line      interface{}
	Source    interface{}
	Tag       map[string]string
	Logtypeid interface{}
	Timings   []*KV
}

func NewLogLine() *LogLine {
	return &LogLine{}
}

func (this *LogLine) Schema() avro.Schema {
	if _LogLine_schema_err != nil {
		panic(_LogLine_schema_err)
	}
	return _LogLine_schema
}

type KV struct {
	Key   string
	Value int64
}

func NewKV() *KV {
	return &KV{}
}

func (this *KV) Schema() avro.Schema {
	if _KV_schema_err != nil {
		panic(_KV_schema_err)
	}
	return _KV_schema
}

// Generated by codegen. Please do not modify.
var _LogLine_schema, _LogLine_schema_err = avro.ParseSchema(`{
    "type": "record",
    "namespace": "avro",
    "name": "logLine",
    "fields": [
        {
            "name": "line",
            "default": null,
            "type": [
                "null",
                "string"
            ]
        },
        {
            "name": "source",
            "default": null,
            "type": [
                "null",
                "string"
            ]
        },
        {
            "name": "tag",
            "default": null,
            "type": [
                "null",
                {
                    "type": "map",
                    "values": "string"
                }
            ]
        },
        {
            "name": "logtypeid",
            "default": null,
            "type": [
                "null",
                "long"
            ]
        },
        {
            "name": "timings",
            "default": null,
            "type": [
                "null",
                {
                    "type": "array",
                    "items": {
                        "type": "record",
                        "name": "KV",
                        "fields": [
                            {
                                "name": "key",
                                "type": "string"
                            },
                            {
                                "name": "value",
                                "type": "long"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}`)

// Generated by codegen. Please do not modify.
var _KV_schema, _KV_schema_err = avro.ParseSchema(`{
    "type": "record",
    "name": "KV",
    "fields": [
        {
            "name": "key",
            "type": "string"
        },
        {
            "name": "value",
            "type": "long"
        }
    ]
}`)
