package interop

import "github.com/stealthly/go-avro"

type SubRecord1 struct {
	Map1    map[string]string
}

func NewSubRecord1() *SubRecord1 {
	return &SubRecord1{
		Map1: make(map[string]string),
	}
}

func (this *SubRecord1) Schema() avro.Schema {
	if _SubRecord1_schema_err != nil {
		panic(_SubRecord1_schema_err)
	}
	return _SubRecord1_schema
}

// Generated by codegen. Please do not modify.
var _SubRecord1_schema, _SubRecord1_schema_err = avro.ParseSchema(`{
    "type": "record",
    "name": "Rec",
    "fields": [
        {
            "name": "map1",
            "type": {
                "type": "map",
                "values": "string"
            }
        }
    ]
}`)
